<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Mari Bergabung Dengan Kami_gmap_canvas</name>
   <tag></tag>
   <elementGuidId>70adb702-5d0f-4331-b661-472ca54857ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gmap_canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gmap_canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gmap_canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dedb809b-033f-49fe-b1ca-0c4e78b3ba55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>948f4444-a93e-4de6-838b-a07342b4fbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>88b24227-4c91-4d47-8098-ce2035829daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gmap_canvas</value>
      <webElementGuid>824b3de7-8632-478f-b904-2f960f5bd3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed</value>
      <webElementGuid>e694557b-b11a-4bcd-aef4-a2f442479e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>682fca95-5a5e-4c31-8766-92393c6cbdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c5b5eb32-6c91-4ce5-9e91-fcc722726e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>698f0bb7-8418-4bfc-93e5-0d7be6126514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90ab7cbf-9b47-447f-b438-7e746f29c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gmap_canvas&quot;)</value>
      <webElementGuid>7c86fb61-fa53-4669-acf2-1fd2e720a32f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gmap_canvas']</value>
      <webElementGuid>e5190fe2-d3b9-4bda-8dc3-985dc2957fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='pricing']/div/section/div/div/iframe</value>
      <webElementGuid>bfc25d9b-87e3-4f80-9475-2c505db3be5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>83c3170f-c53c-4e80-acce-6fbc26a30c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gmap_canvas' and @src = 'https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed']</value>
      <webElementGuid>a39aac56-e316-4b3b-90d3-72290c2a8b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
