<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lokasi Bank Sampah Malang_gmap_canvas</name>
   <tag></tag>
   <elementGuidId>a63e30a6-e3ba-4c68-acc5-f129511827a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gmap_canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gmap_canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gmap_canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>eaf2685a-08c5-43ed-aa59-dac888d9df87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>6ec61132-0a26-4852-925d-0d37eeeb1fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>4e0253af-e8d5-4f13-9e0a-689e83598730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gmap_canvas</value>
      <webElementGuid>8305f889-9a6e-480f-9df8-2f21e84dce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed</value>
      <webElementGuid>41e37220-b60a-4187-8db4-81d0c8b2ff08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ff6cce4-0fc0-45d0-af6a-75d82159c2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fa6cc202-3bd6-45e3-b67b-72eae30c73b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24ad402b-03fd-4ac9-a5d4-aa476a735bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9173d248-9dc9-4189-afd2-51159e68d092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gmap_canvas&quot;)</value>
      <webElementGuid>b2675d9a-9313-4537-bf17-65b69e5e3438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gmap_canvas']</value>
      <webElementGuid>84c4253b-4a94-457d-a79f-b23316b4739a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='pricing']/div/section/div/div/iframe</value>
      <webElementGuid>3e73b788-4414-49cb-8ad8-d704a52fe197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c949634d-f63e-4a0e-bbf1-90e5084708e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gmap_canvas' and @src = 'https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed']</value>
      <webElementGuid>63819ce3-ba7a-4499-a816-14b8f5577cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
