<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Mari Bergabung Dengan Kami_gmap_canvas</name>
   <tag></tag>
   <elementGuidId>a73e883b-6dea-4520-b678-94de1295ef88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gmap_canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gmap_canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gmap_canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b1646608-c33c-4073-922c-afc2656e124a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>a5232e25-d70b-414f-8bd4-dc2ec34022b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b90f247c-f6e1-4ba1-88b5-6d08e16b5a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gmap_canvas</value>
      <webElementGuid>1de3430d-be7c-4937-a6ac-ac1c58f33f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed</value>
      <webElementGuid>0c41b719-d26d-40de-9bc0-bcbd7d8e9b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00418025-b5eb-4a77-8c81-bbb742e4cc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d6c1d750-56cf-4cad-b744-64b5737b0fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4086f417-e232-4251-aa94-909aaeda6d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c280c1b4-41db-4a91-bb13-532bce6889aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gmap_canvas&quot;)</value>
      <webElementGuid>a4be2c20-e710-4d3b-a5ec-ed5f26f07646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gmap_canvas']</value>
      <webElementGuid>e23f352e-622f-4d29-8ab9-d2c655f75b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='pricing']/div/section/div/div/iframe</value>
      <webElementGuid>8c7804d6-c054-40bf-8ae0-64b8862dd1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>866f454c-0efe-4eb4-996e-bb609e4a0658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gmap_canvas' and @src = 'https://maps.google.com/maps?q=bank+sampah&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed']</value>
      <webElementGuid>3d5bea8c-2695-46a3-808f-a2ef6e06cff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
